version: '3.4'

services:

  identity-api:
    image: eshop/identity.api
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile


  basket-api:
    image: eshop/basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - identity-api

  catalog-api:
    image: eshop/catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  ordering-api:
    image: eshop/ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  ordering-backgroundtasks:
    image: eshop/ordering.backgroundtasks
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile

  payment-api:
    image: eshop/payment.api
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile

  webhooks-api:
    image: eshop/webhooks.api
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile

  mobileshoppingagg:
    image: eshop/mobileshoppingagg
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - identity-api
      - ordering-api
      - catalog-api
      - basket-api

  webshoppingagg:
    image: eshop/webshoppingagg
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - identity-api
      - ordering-api
      - catalog-api
      - basket-api

  ordering-signalrhub:
    image: eshop/ordering.signalrhub
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - identity-api
      - ordering-api
      - catalog-api
      - basket-api

  webstatus:
    image: eshop/webstatus
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile

  webspa:
    image: eshop/webspa
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
    depends_on:
      - webshoppingagg

  webmvc:
    image: eshop/webmvc
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg

  webhooks-client:
    image: eshop/webhooks.client
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api
